# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(292, 376)
        Form.setStyleSheet("/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(39, 39, 39, 255),stop:1 rgba(58, 58, 58, 255));\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar \n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(39, 39, 39, 255),stop:1 rgba(58, 58, 58, 255));   \n"
"    border: none;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item \n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected \n"
"{\n"
"    background-color: #303030;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed \n"
"{\n"
"    background-color: #1c1c1c;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #1c1c1c;\n"
"    border: 1px solid #222;\n"
"    padding: 4px;\n"
"    padding-right: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #ff6530;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolBar-----*/\n"
"QToolBar \n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(58, 58, 58, 255),stop:1 rgba(39, 39, 39, 255));\n"
"    border: none;\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolBar::handle\n"
"{\n"
"    width: 10px;\n"
"    margin: 4px 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolBar::separator\n"
"{\n"
"    width: 1px;\n"
"    margin: 0px 4px;\n"
"    background-color: #565656;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QDialog-----*/\n"
"QDialog \n"
"{\n"
"    background-color: #1c1c1c;\n"
"    border: 1px solid #000;\n"
"    border-radius: 1px;\n"
"    color: #fff;\n"
"    opacity: 20;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPlainTextEdit-----*/\n"
"QPlainTextEdit\n"
"{\n"
"    color: #fff;\n"
"    background-color: #1b1b1b;\n"
"    selection-background-color: #bcbcbc;\n"
"    selection-color: #000;\n"
"    border: 1px solid darkgray;\n"
"    border-top: none;\n"
"    border-radius : 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTabBar-----*/\n"
"QTabBar \n"
"{\n"
"    background-color: transparent;\n"
"    margin-top:0px;\n"
"    border: 1px solid gray;\n"
"}\n"
"\n"
"\n"
"QTabBar::tear \n"
"{\n"
"    width: 10px; \n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabWidget::tab-bar \n"
"{\n"
"    border:none;\n"
"    left: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab \n"
"{\n"
"    font: 7pt \"Verdana\";\n"
"    font: bold;\n"
"    color: #fff;\n"
"    padding-left: 15px; \n"
"    padding-right: 15px; \n"
"    height: 25px;\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane \n"
"{\n"
"    border: 1px solid rgb(71, 71, 71); \n"
"    margin-top: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected \n"
"{\n"
"    color: #b1b1b1; \n"
"    border: 1px solid #1b1b1b;\n"
"    background-color: #1b1b1b;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected \n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(101, 101, 101, 255),stop:1 rgba(66, 66, 66, 255));\n"
"    border: 1px solid #414141;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected:hover \n"
"{\n"
"    color: #fff; \n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton \n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(82, 82, 82, 255),stop:0.995192 rgba(75, 75, 75, 255));\n"
"    color: #000;\n"
"    border: 1px solid #606060;\n"
"    border-radius: 2px;\n"
"    padding: 2px;\n"
"    margin-right: 5px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: #8b8b8b;\n"
"    \n"
"}\n"
"\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #7c7c7c;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:checked\n"
"{\n"
"    background-color: #7c7c7c;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton \n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(82, 82, 82, 255),stop:0.995192 rgba(75, 75, 75, 255));\n"
"    color: #000;\n"
"    border: 1px solid #606060;\n"
"    border-radius: 2px;\n"
"    padding: 2px;\n"
"    margin-right: 5px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QToolButton:hover\n"
"{\n"
"    background-color: #8b8b8b;\n"
"    \n"
"}\n"
"\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: #7c7c7c;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: #7c7c7c;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QDockWidget-----*/\n"
" QDockWidget\n"
"{\n"
"    color : #000;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QDockWidget::title \n"
"{\n"
"    background-color: #888888;\n"
"    border: 1px solid rgb(58, 58, 58);\n"
"    padding: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDockWidget::close-button\n"
"{\n"
"    max-width: 14px;\n"
"    max-height: 14px;\n"
"    margin-top:1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDockWidget::float-button\n"
"{\n"
"    max-width: 14px;\n"
"    max-height: 14px;\n"
"    margin-top:1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDockWidget::close-button:hover\n"
"{\n"
"    border: none;\n"
"    background-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QDockWidget::float-button:hover\n"
"{\n"
"    border: none;\n"
"    background-color: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeWidget-----*/\n"
"QTreeWidget\n"
"{\n"
"    show-decoration-selected: 0;\n"
"    selection-background-color: transparent; /* Used on Mac */\n"
"    selection-color: #fff; /* Used on Mac */\n"
"    background-color: #292929;\n"
"    border: 1px solid gray;\n"
"    padding-top : 5px;\n"
"    color: #fff;\n"
"    font: 8pt;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    color:#000;\n"
"    background-color: #ff6530;\n"
"    border-radius: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:!selected:hover\n"
"{\n"
"    color:#000;\n"
"    background-color: #8b8b8b;\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings \n"
"{\n"
"    image: url(://tree-closed.png);\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  \n"
"{\n"
"    image: url(://tree-open.png);\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QListView-----*/\n"
"QListView \n"
"{\n"
"    border : none;\n"
"    background-color: #292929;\n"
"    color: white;\n"
"    show-decoration-selected: 1; /* make the selection span the entire width of the view */\n"
"    outline: 0;\n"
"    border: 1px solid gray;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::disabled \n"
"{\n"
"    background-color: #656565;\n"
"    color: #1b1b1b;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item \n"
"{\n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:alternate \n"
"{\n"
"    background-color: #4a4b4d;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected \n"
"{\n"
"    border: 1px solid #6a6ea9;\n"
"    border: none;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:!active \n"
"{\n"
"    background-color: #ff6530;\n"
"    border: none;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:active \n"
"{\n"
"    background-color: #ff6530;\n"
"    border: none;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:hover {\n"
"    color:#000;\n"
"    background-color: #8b8b8b;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal \n"
"{\n"
"    background-color: #1b1b1b;\n"
"    height: 17px;\n"
"    margin-bottom: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"    border-radius : 5px;\n"
"    background-color: #ff6530;\n"
"    min-width: 50px;\n"
"    height : 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal \n"
"{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    width: 0px;\n"
"\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover\n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal:pressed\n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    border-radius :0px;\n"
"    width: 0px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:hover \n"
"{\n"
"    background-color: transprarent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:pressed \n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:left-arrow:horizontal \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::right-arrow:horizontal \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical \n"
"{\n"
"    background-color: #1b1b1b;\n"
"    border : none;\n"
"    width: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"    background-color: #ff6530;\n"
"    min-height: 80px;\n"
"    width : 10px;\n"
"    margin: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 0px;\n"
"    subcontrol-position: none;\n"
"    subcontrol-origin: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical:hover \n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:pressed \n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical \n"
"{\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical:hover \n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical:pressed \n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:vertical \n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical \n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QStatusBar-----*/\n"
"QStatusBar \n"
"{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(39, 39, 39, 255),stop:1 rgba(58, 58, 58, 255));\n"
"\n"
"}\n"
"\n"
"\n"
"QStatusBar::item \n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(180, 220, 75, 50))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 70, 75, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 70, 75, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 120, 75, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 120, 75, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(180, 120, 75, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(180, 170, 75, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(110, 170, 75, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(40, 170, 75, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(180, 70, 75, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(110, 220, 75, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_16 = QtWidgets.QPushButton(Form)
        self.pushButton_16.setGeometry(QtCore.QRect(40, 220, 75, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(180, 270, 75, 49))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_17 = QtWidgets.QPushButton(Form)
        self.pushButton_17.setGeometry(QtCore.QRect(40, 270, 75, 49))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(110, 270, 75, 49))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_18 = QtWidgets.QPushButton(Form)
        self.pushButton_18.setGeometry(QtCore.QRect(110, 319, 75, 49))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(Form)
        self.pushButton_19.setGeometry(QtCore.QRect(180, 319, 75, 49))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(30, 20, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButton_20 = QtWidgets.QPushButton(Form)
        self.pushButton_20.setGeometry(QtCore.QRect(40, 319, 75, 49))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Abdullah Calculator"))
        self.pushButton.setText(_translate("Form", "="))
        self.pushButton_2.setText(_translate("Form", "8"))
        self.pushButton_3.setText(_translate("Form", "7"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_7.setText(_translate("Form", "3"))
        self.pushButton_8.setText(_translate("Form", "2"))
        self.pushButton_9.setText(_translate("Form", "1"))
        self.pushButton_10.setText(_translate("Form", "9"))
        self.pushButton_11.setText(_translate("Form", "+"))
        self.pushButton_16.setText(_translate("Form", "0"))
        self.pushButton_12.setText(_translate("Form", "/"))
        self.pushButton_17.setText(_translate("Form", "x"))
        self.pushButton_13.setText(_translate("Form", "-"))
        self.pushButton_18.setText(_translate("Form", "Clear"))
        self.pushButton_19.setText(_translate("Form", "Delete"))
        self.pushButton_20.setText(_translate("Form", "•"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
